import { Preset } from '../types';

export const shelvesPreset: Preset = {
  id: 'b2b-shelves',
  name: 'Полки',
  icon: 'LayoutGrid',
  description: 'Размещение товаров на рекламных полках',
  data: [
    {
      campaign_name: 'Перемычка_екоми',
      products_count: '25 товаров - SCANPUC, KOMIS, и ещё 5 брендов',
      category: 'Брендформация',
      status: 'Отключена',
      tags: 'Поиск, Показ товаров, Внимание!',
      bid: '100,15 ₽',
      budget: '300 ₽ в день',
      impressions: '0',
      reach: '0',
      clicks: '0',
      ctr: '0 %',
      orders: '0',
      conversion: '0 %',
      revenue: '0 ₽',
      cpo: '—',
      expenses: '0 ₽'
    },
    {
      campaign_name: 'Влаг.питание Thermaltake/Магризион (19.09 - 02.10)',
      products_count: '5 товаров - Thermaltake',
      category: 'Бренд читтеров',
      status: 'Отключена',
      tags: 'Поиск, Показ товаров, Внимание!',
      bid: '1 000,00 ₽',
      budget: '1 090 ₽ в день',
      impressions: '0',
      reach: '0',
      clicks: '0',
      ctr: '0 %',
      orders: '0',
      conversion: '0 %',
      revenue: '0 ₽',
      cpo: '—',
      expenses: '0 ₽'
    },
    {
      campaign_name: 'Гарнитуры для телефонов_екоми',
      products_count: '18 товаров - Gefix, Reain, unify и др.',
      category: 'Маршшины и Грилла-ны',
      status: 'Отключена',
      tags: 'Поиск, Показ товаров, Внимание!',
      bid: '100 ₽',
      budget: '300 ₽ в день',
      impressions: '0',
      reach: '0',
      clicks: '0',
      ctr: '0 %',
      orders: '0',
      conversion: '0 %',
      revenue: '0 ₽',
      cpo: '—',
      expenses: '0 ₽'
    },
    {
      campaign_name: 'Холодильники для насадок_екоми',
      products_count: '20 товаров - ATEL UNIT, Breun, и ещё 11 брендов',
      category: 'Холодильники для открытых поводов',
      status: 'Отключена',
      tags: 'Поиск, Показ товаров, Внимание!',
      bid: '1 300,00 ₽',
      budget: '2 020 ₽ в день',
      impressions: '0',
      reach: '0',
      clicks: '0',
      ctr: '0 %',
      orders: '0',
      conversion: '0 %',
      revenue: '0 ₽',
      cpo: '—',
      expenses: '0 ₽'
    },
    {
      campaign_name: 'Дырокол_Хо-ппы_екоми',
      products_count: '20 товаров - NYTONE',
      category: 'Дыроколы',
      status: 'Отключена',
      tags: 'Поиск, Показ товаров, Внимание!',
      bid: '110,35 ₽',
      budget: '300 ₽ в день',
      impressions: '0',
      reach: '0',
      clicks: '0',
      ctr: '0 %',
      orders: '0',
      conversion: '0 %',
      revenue: '0 ₽',
      cpo: '—',
      expenses: '0 ₽'
    }
  ]
};

